# Generated by Django 4.0.1 on 2023-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0021_auto_20220317_0659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'get_latest_by': ''},
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
