# Generated by Django 4.0.1 on 2023-01-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0022_alter_addressmodel_options_addressmodel_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmodel',
            options={'get_latest_by': ('-created',)},
        ),
    ]
