# Generated by Django 4.0.1 on 2023-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0024_coupon_cart_cart_id_cart_coupon_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
