# Generated by Django 4.0.1 on 2023-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0025_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
