# Generated by Django 4.0.1 on 2023-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0027_alter_cart_options_cart_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindishmodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
