# Generated by Django 4.0.1 on 2023-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0029_remove_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
