# Generated by Django 4.0.1 on 2023-01-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0030_remove_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
