# Generated by Django 4.0.1 on 2023-02-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0037_coupon_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffine_site.maindishmodel')),
            ],
        ),
    ]
