# Generated by Django 4.0.1 on 2023-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0038_customersfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentandrating',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
