# Generated by Django 4.0.1 on 2023-02-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0042_marketingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
