# Generated by Django 4.0.1 on 2023-02-18 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0043_alter_addressmodel_city_alter_addressmodel_landmark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingModel',
        ),
    ]
