# Generated by Django 4.0.1 on 2023-02-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0044_delete_marketingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('CART', 'CART'), ('MENU', 'MENU')], max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiffine_site.maindishmodel')),
            ],
        ),
    ]
