# Generated by Django 4.0.1 on 2023-02-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0046_remove_peoplefavorite_food_peoplefavorite_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindishmodel',
            name='rating',
            field=models.FloatField(default=3.7, null=True),
        ),
    ]
