# Generated by Django 4.0.1 on 2023-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0043_alter_addressmodel_city_alter_addressmodel_landmark_and_more'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannersmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='bannersmodel',
            name='validity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannersmodel',
            name='banner_type',
            field=models.CharField(choices=[('HOME_CAROSEL', 'HOME_CAROSEL'), ('MENU_CAROCEL', 'MENU_CAROCEL'), ('CART_IMG', 'CART_IMG'), ('ADDRESS_IMG', 'ADDRESS_IMG'), ('PAYMENT_IMG', 'PAYMENT_IMG'), ('ADDRESS-COUPON', 'ADDRESS-COUPON')], max_length=25, null=True),
        ),
        migrations.RemoveField(
            model_name='bannersmodel',
            name='itmes',
        ),
        migrations.AddField(
            model_name='bannersmodel',
            name='itmes',
            field=models.ManyToManyField(null=True, to='tiffine_site.MainDishModel'),
        ),
    ]
