# Generated by Django 4.0.1 on 2023-02-18 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiffine_site', '0043_alter_addressmodel_city_alter_addressmodel_landmark_and_more'),
        ('checkout', '0003_alter_bannersmodel_itmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannersmodel',
            name='itmes',
        ),
        migrations.AddField(
            model_name='bannersmodel',
            name='itmes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tiffine_site.maindishmodel'),
        ),
    ]
