# Generated by Django 4.0.1 on 2023-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_payment_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_signature',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
