# Generated by Django 4.0.1 on 2023-02-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_payment_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='time_slot',
            field=models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER')], max_length=15, null=True),
        ),
    ]
