# Generated by Django 4.0.1 on 2023-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ordermodel_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
