# Generated by Django 4.0.1 on 2023-02-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_ordermodel_payment_type_alter_ordermodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment_response',
            field=models.JSONField(null=True),
        ),
    ]
