# Generated by Django 4.0.1 on 2023-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_ordermodel_payment_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DELIVERD', 'DELIVERD')], default='PENDING', max_length=10, null=True),
        ),
    ]
