# Generated by Django 4.0.1 on 2023-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordermodel_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('DELIVERD', 'DELIVERD'), ('CANCEL', 'CANCEL')], default='PENDING', max_length=10, null=True),
        ),
    ]
